#!/command/with-contenv sh
# shellcheck shell=sh

set -eu

. /usr/local/bin/backend-functions

log "INIT-ADDUSER" "Starting init-adduser script..."

if [ "$(id -g nordvpn)" -ne "$pgid" ]; then
    log "INIT-ADDUSER" "Updating nordvpn group ID from $(id -g nordvpn) to $pgid"
    groupmod --non-unique --gid "$pgid" nordvpn
fi

if [ "$(id -u nordvpn)" -ne "$puid" ]; then
    log "INIT-ADDUSER" "Updating nordvpn user ID from $(id -u nordvpn) to $puid"
    usermod --non-unique --uid "$puid" nordvpn
fi

log "INIT-ADDUSER" "init-adduser script completed successfully"
exit 0
