#!/command/with-contenv sh
# shellcheck shell=sh

set -eu

. /usr/local/bin/backend-functions

SCRIPT_NAME="INIT-ADDUSER"

log "$SCRIPT_NAME" "Starting user initialization"

if [ "$(id -g nordvpn)" -ne "$pgid" ]; then
    log "$SCRIPT_NAME" "Updating nordvpn group ID from $(id -g nordvpn) to $pgid"
    groupmod --non-unique --gid "$pgid" nordvpn
fi

if [ "$(id -u nordvpn)" -ne "$puid" ]; then
    log "$SCRIPT_NAME" "Updating nordvpn user ID from $(id -u nordvpn) to $puid"
    usermod --non-unique --uid "$puid" nordvpn
fi

log "$SCRIPT_NAME" "User initialization completed"
exit 0
