#!/bin/sh
# OpenVPN up script — apply pushed DNS to /etc/resolv.conf
# Part of azinchen/nordvpn (MIT)

[ "${PEER_DNS}" = "no" ] && exit 0

# Back up current resolv.conf so down.sh can restore it
[ -f /etc/resolv.conf ] && cp /etc/resolv.conf "/etc/resolv.conf.ovpn-${dev}"

# Collect DNS and domain options pushed by the server
_nameservers=""
_domains=""
n=1
while : ; do
    _opt=$(printenv "foreign_option_${n}" 2>/dev/null) || true
    [ -z "$_opt" ] && break
    case "$_opt" in
        "dhcp-option DNS "*)  _nameservers="${_nameservers}${_opt#dhcp-option DNS }${IFS%%?}" ;;
        "dhcp-option DOMAIN "*) _domains="${_domains}${_opt#dhcp-option DOMAIN } " ;;
    esac
    n=$((n + 1))
done

[ -z "$_nameservers" ] && exit 0

# Write new resolv.conf
{
    printf '# Generated by OpenVPN (%s)\n' "$dev"
    [ -n "$_domains" ] && printf 'search %s\n' "$(echo $_domains)"
    for _ns in $_nameservers; do
        printf 'nameserver %s\n' "$_ns"
    done
} > /etc/resolv.conf
chmod 644 /etc/resolv.conf

exit 0
