#!/bin/sh
# OpenVPN up script — apply pushed DNS to /etc/resolv.conf
# Part of azinchen/nordvpn (MIT)

# OpenVPN builds a fresh environment for its scripts (container env vars are
# absent here), so re-import the ones this script and gateway-dns-update
# depend on from s6's container-environment store.
for _v in DNS PEER_DNS GATEWAY_DNS FORWARD_FROM; do
    if [ -f "/run/s6/container_environment/$_v" ]; then
        export "$_v"="$(cat "/run/s6/container_environment/$_v")"
    fi
done

# DNS=off (preferred) or legacy PEER_DNS=no: leave resolv.conf untouched
[ "${DNS:-}" = "off" ] && exit 0
[ "${PEER_DNS:-}" = "no" ] && exit 0

# Back up current resolv.conf so down.sh can restore it
[ -f /etc/resolv.conf ] && cp /etc/resolv.conf "/etc/resolv.conf.ovpn-${dev}"

# Collect DNS and domain options pushed by the server
_nameservers=""
_domains=""
n=1
while : ; do
    _opt=$(printenv "foreign_option_${n}" 2>/dev/null) || true
    [ -z "$_opt" ] && break
    case "$_opt" in
        "dhcp-option DNS "*)  _nameservers="${_nameservers}${_opt#dhcp-option DNS }${IFS%%?}" ;;
        "dhcp-option DOMAIN "*) _domains="${_domains}${_opt#dhcp-option DOMAIN } " ;;
    esac
    n=$((n + 1))
done

# Keep the GATEWAY_DNS=redirect DNAT pointed at the current resolvers
# (no-op in the other modes; word splitting of the list is intended)
# shellcheck disable=SC2086
/usr/local/bin/gateway-dns-update $_nameservers || true

[ -z "$_nameservers" ] && exit 0

# Write new resolv.conf
{
    printf '# Generated by OpenVPN (%s)\n' "$dev"
    [ -n "$_domains" ] && printf 'search %s\n' "$(echo $_domains)"
    for _ns in $_nameservers; do
        printf 'nameserver %s\n' "$_ns"
    done
} > /etc/resolv.conf
chmod 644 /etc/resolv.conf

exit 0
