#!/command/with-contenv sh
# shellcheck shell=sh

set -eu

. /usr/local/bin/backend-functions

SCRIPT_NAME="SERVICE-NORDVPN"

log "$SCRIPT_NAME" "Stopping NordVPN service"

log "$SCRIPT_NAME" "Cleaning up VPN firewall rules"
run4 -F VPN-SERVER

log "$SCRIPT_NAME" "Disconnecting OpenVPN"
echo "signal SIGTERM" | nc -U "$mgmtsockfile"
sleep 5

log "$SCRIPT_NAME" "NordVPN service stopped"
exit 0
