#!/command/with-contenv sh
# shellcheck shell=sh

set -eu

echo "[SERVICE] Starting nordvpnd service..."

authfile="/tmp/auth"
ovpnfile="/tmp/nordvpn.ovpn"

echo "[SERVICE] Using auth file: $authfile"
echo "[SERVICE] Using OpenVPN config file: $ovpnfile"
echo "[SERVICE] Starting OpenVPN with options: ${OPENVPN_OPTS:-none}"

exec sg nordvpn -c "openvpn --config $ovpnfile --auth-user-pass $authfile --auth-nocache ${OPENVPN_OPTS}"
