#!/command/with-contenv bash
# shellcheck shell=bash

set -euo pipefail

authfile="/tmp/auth"

echo "Create auth file"

echo "$USER" > "$authfile"
echo "$PASS" >> "$authfile"
chmod 0600 "$authfile"
chown nordvpn:nordvpn "$authfile"

exit 0
