#!/command/with-contenv sh
# shellcheck shell=sh

set -eu

echo "[INIT-CREATEAUTH] Starting init-createauth script..."

. /usr/local/bin/backend-functions

authfile="/run/xt/auth"

echo "$user" > "$authfile"
echo "$pass" >> "$authfile"
chmod 0600 "$authfile"
chown nordvpn:nordvpn "$authfile"

echo "[INIT-CREATEAUTH] init-createauth script completed successfully"
exit 0
