#!/command/with-contenv sh
# shellcheck shell=sh

set -eu

. /usr/local/bin/backend-functions

SCRIPT_NAME="INIT-CREATEAUTH"

log "$SCRIPT_NAME" "Starting init-createauth script..."

echo "$user" > "$authfile"
echo "$pass" >> "$authfile"
chmod 0600 "$authfile"
chown nordvpn:nordvpn "$authfile"

log "$SCRIPT_NAME" "init-createauth script completed successfully"
exit 0
