name: Build_and_Deploy_image

on:
  push:

env:
  PLATFORMS: "linux/amd64,linux/386,linux/arm64,linux/arm/v7,linux/arm/v6,linux/ppc64le"

jobs:
  update_config_build_and_deploy:
    name: Build and publish Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Get branch name
        id: branch
        shell: bash
        run: |
          branch=$(echo ${GITHUB_REF} | sed -e "s/.*\///g")
          echo "::set-output name=branch::$branch"
          echo "Action branch=$branch"

      - name: Get build date
        id: date
        shell: bash
        run: |
          date=`date +%F_%H-%M-%S`
          echo "::set-output name=date::$date"
          echo "Build date=$date"

      - name: Login to DockerHub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0
        with:
          platforms: ${{ env.PLATFORMS }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.4.1

      - name: Build and push latest and sha
        if: ${{ steps.branch.outputs.branch == 'main' || steps.branch.outputs.branch == 'master' }}
        uses: docker/build-push-action@v2.6.1
        with:
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: |
            ${{ github.repository }}:latest-${{ steps.date.outputs.date }}
            ghcr.io/${{ github.repository }}:latest-${{ steps.date.outputs.date }}
            ${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:latest

      - name: Build and push branch
        if: ${{ steps.branch.outputs.branch != 'main' && steps.branch.outputs.branch != 'master' }}
        uses: docker/build-push-action@v2.6.1
        with:
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: |
            ${{ github.repository }}:${{ steps.branch.outputs.branch }}
            ghcr.io/${{ github.repository }}:${{ steps.branch.outputs.branch }}

      - name: Update repo description
        if: ${{ steps.branch.outputs.branch == 'main' || steps.branch.outputs.branch == 'master' }}
        uses: peter-evans/dockerhub-description@v2.4.3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ github.repository }}
          short-description: ${{ github.event.repository.description }}
