name: Build and Deploy image

on:
  push:

permissions:
  contents: read
  packages: write
  actions: read
  security-events: write  # Required for called security workflows to upload SARIF files

env:
  PLATFORMS: "linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/riscv64,linux/s390x"

jobs:
  update_config_build_and_deploy:
    name: Build and publish Docker image
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.git.outputs.image_tag }}
      is_tag: ${{ steps.git.outputs.is_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Get branch name
        id: git
        shell: bash
        run: |
          IS_TAG=false
          if [[ ${GITHUB_REF} == *"/tags/"* ]]; then
            IS_TAG=true
          fi

          BRANCH_NAME=$(echo ${GITHUB_REF} | sed -e "s/.*\///g")

          if [[ ${IS_TAG} == 'true' ]]; then
            IMAGE_TAG=${BRANCH_NAME:1}
          else
            IMAGE_TAG=${BRANCH_NAME}
          fi

          echo "image_tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT
          echo "is_tag=${IS_TAG}" >> $GITHUB_OUTPUT

          echo "Action branch=${BRANCH_NAME} tag=${IS_TAG} ref=${GITHUB_REF} image_tag=${IMAGE_TAG}"

      - name: Login to DockerHub
        uses: docker/login-action@v3.5.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0
        with:
          platforms: ${{ env.PLATFORMS }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Build and push ${{ github.repository }}:${{ env.image_tag }}
        uses: docker/build-push-action@v6.18.0
        with:
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: |
            ${{ github.repository }}:${{ steps.git.outputs.image_tag }}
            ghcr.io/${{ github.repository }}:${{ steps.git.outputs.image_tag }}

      - name: Build and push latest image
        if: ${{ steps.git.outputs.is_tag == 'true' }}
        uses: docker/build-push-action@v6.18.0
        with:
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: |
            ${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:latest

      - name: Update repo description
        if: ${{ steps.git.outputs.is_tag == 'true' }}
        uses: peter-evans/dockerhub-description@v4.0.2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ github.repository }}
          short-description: ${{ github.event.repository.description }}

  security-scan-tag:
    name: Run security scan on deployed image
    needs: update_config_build_and_deploy
    uses: ./.github/workflows/docker-image-security.yml
    with:
      image_tag: ${{ needs.update_config_build_and_deploy.outputs.image_tag }}
    secrets: inherit

  security-scan-latest:
    name: Run security scan on latest image
    needs: update_config_build_and_deploy
    if: ${{ needs.update_config_build_and_deploy.outputs.is_tag == 'true' }}
    uses: ./.github/workflows/docker-image-security.yml
    with:
      image_tag: 'latest'
    secrets: inherit
