name: Update APK Versions
permissions:
  contents: write
  pull-requests: write

on:
  schedule:
    - cron: 0 3 * * *
  workflow_dispatch:

jobs:
  update-apk-versions:
    name: Update APK Versions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Run update-apk-versions.sh Script
        id: update_packages
        run: |
          chmod +x ./scripts/update-apk-versions.sh
          # Pass the path to the Dockerfile; adjust if your Dockerfile is located elsewhere.
          ./scripts/update-apk-versions.sh Dockerfile

          TEMPLATE_DATE=$(date +%y%m%d)
          echo "template_date=${TEMPLATE_DATE}" >> $GITHUB_ENV
          echo "template_date=${TEMPLATE_DATE}" >> $GITHUB_OUTPUT
          echo "Base date=${TEMPLATE_DATE}"

      - name: Create Pull Request
        if: steps.update_packages.outputs.has_updates == 'true'
        uses: peter-evans/create-pull-request@v7.0.8
        with:
          branch: apkupdaterbot/packageversionupdate
          commit-message: "chore: update ${{ steps.update_packages.outputs.updated_count }} APK package(s) on ${{ steps.update_packages.outputs.template_date }}"
          delete-branch: true
          title: "chore: update ${{ steps.update_packages.outputs.updated_count }} APK package(s) - ${{ steps.update_packages.outputs.template_date }}"
          body: |
            ## 📦 APK Package Updates
            
            **Date**: ${{ steps.update_packages.outputs.template_date }}
            **Packages updated**: ${{ steps.update_packages.outputs.updated_count }} of ${{ steps.update_packages.outputs.total_packages }} checked
            
            ### Updated Packages:
            ${{ steps.update_packages.outputs.packages_updated }}
            
            ### Changes:
            - Updated Alpine Linux package versions in Dockerfile
            - All packages checked against Alpine v3.22 repositories (main and community)
            
            ---
            🤖 Auto-generated by [create-pull-request](https://github.com/peter-evans/create-pull-request)
          labels: |
            dependencies
            github_actions
            automated

      - name: No Updates Available
        if: steps.update_packages.outputs.has_updates == 'false'
        run: |
          echo "✅ All ${{ steps.update_packages.outputs.total_packages }} APK packages are up-to-date. No PR needed."
  